# Generated by Django 4.2 on 2023-06-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatars',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.FileField(upload_to='file/', verbose_name='文件地址')),
            ],
            options={
                'verbose_name_plural': '文件管理',
            },
        ),
        migrations.RemoveField(
            model_name='paper',
            name='user',
        ),
        migrations.DeleteModel(
            name='MyPaper',
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
    ]
