# Generated by Django 4.2 on 2023-07-04 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_avatars_remove_paper_user_delete_mypaper_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solvent',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='溶剂名称')),
            ],
            options={
                'verbose_name_plural': '溶剂',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='样品名称')),
                ('concentration', models.CharField(blank=True, max_length=128, null=True, verbose_name='样品浓度')),
                ('purity', models.CharField(blank=True, max_length=128, null=True, verbose_name='样品纯度')),
                ('volume', models.CharField(blank=True, max_length=128, null=True, verbose_name='样品体积')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('solvent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.solvent', verbose_name='溶剂')),
            ],
            options={
                'verbose_name_plural': '样品',
            },
        ),
    ]
