# Generated by Django 4.2 on 2023-07-04 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_solvent_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='solvent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.solvent', verbose_name='溶剂'),
        ),
    ]
