# Generated by Django 4.2 on 2023-07-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_sample_solvent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('university', models.CharField(max_length=32, verbose_name='大学')),
                ('ranking', models.IntegerField(verbose_name='最低录取排名')),
            ],
            options={
                'verbose_name_plural': '大学录取信息',
            },
        ),
    ]
