# Generated by Django 4.2 on 2023-07-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='goal',
            field=models.CharField(max_length=64, null=True, verbose_name='最低录取分数'),
        ),
        migrations.AddField(
            model_name='score',
            name='piecewise',
            field=models.CharField(max_length=64, null=True, verbose_name='大学分段'),
        ),
        migrations.AddField(
            model_name='score',
            name='type',
            field=models.CharField(max_length=64, null=True, verbose_name='大学类型'),
        ),
        migrations.AddField(
            model_name='score',
            name='year',
            field=models.CharField(max_length=64, null=True, verbose_name='年份'),
        ),
        migrations.AlterField(
            model_name='score',
            name='ranking',
            field=models.IntegerField(null=True, verbose_name='最低录取排名'),
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.DeleteModel(
            name='Solvent',
        ),
    ]
